In [31]:
# read csv files from data folder and print the first 5 rows of each file
import pandas as pd
import pathlib

path = pathlib.Path("C:/Users/mamad/Documents/Databricks/sales_data_engineering_pipeline/data/raw/customers.csv")
customers_df = pd.read_csv(path)
display(customers_df)

,customer_id,first_name,last_name,email,city,country,signup_date
0,C001,Alice,Martin,alice.martin@email.com,Paris,France,2022-01-15
1,C002,Bob,Dupont,bob.dupont@email.com,Lyon,France,2022-03-22
2,C003,Clara,Smith,clara.smith@email.com,London,UK,2022-05-10
3,C004,David,Johnson,david.j@email.com,New York,USA,2022-07-08
4,C005,Eva,Müller,eva.muller@email.com,Berlin,Germany,2022-09-30
5,C006,Frank,Rossi,frank.rossi@email.com,Rome,Italy,2023-01-12
6,C007,Grace,Lee,grace.lee@email.com,Seoul,South Korea,2023-03-05
7,C008,Hugo,Garcia,hugo.garcia@email.com,Madrid,Spain,2023-05-18
8,C009,Iris,Tanaka,iris.tanaka@email.com,Tokyo,Japan,2023-07-22
9,C010,Jack,Brown,jack.brown@email.com,Sydney,Australia,2023-10-01
10,C011,Karen,White,NaN,Chicago,USA,2023-11-14
11,C012,Leo,Fernandez,leo.f@email.com,Sao Paulo,Brazil,2024-01-09

In [39]:
# Drop duplicate rows from customers_df
customers_df = customers_df.drop_duplicates(subset=["customer_id"])
# Put signup_date column to datetime format
customers_df["signup_date"] = pd.to_datetime(customers_df["signup_date"], errors="coerce")
# FFill missing values in email to unknown@unknown.com
customers_df["email"] = customers_df["email"].fillna("unknown@unknown.com")
# Combine full name column from first_name and last_name columns and delete space with strip
customers_df["full_name"] = (customers_df["first_name"].str.strip() + " " + customers_df["last_name"].str.strip()).str.strip()
# Reste index of customers_df after dropping duplicates
customers_df = customers_df.reset_index(drop=True)
display(customers_df)

,customer_id,first_name,last_name,email,city,country,signup_date,full_name
0,C001,Alice,Martin,alice.martin@email.com,Paris,France,2022-01-15,Alice Martin
1,C002,Bob,Dupont,bob.dupont@email.com,Lyon,France,2022-03-22,Bob Dupont
2,C003,Clara,Smith,clara.smith@email.com,London,UK,2022-05-10,Clara Smith
3,C004,David,Johnson,david.j@email.com,New York,USA,2022-07-08,David Johnson
4,C005,Eva,Müller,eva.muller@email.com,Berlin,Germany,2022-09-30,Eva Müller
5,C006,Frank,Rossi,frank.rossi@email.com,Rome,Italy,2023-01-12,Frank Rossi
6,C007,Grace,Lee,grace.lee@email.com,Seoul,South Korea,2023-03-05,Grace Lee
7,C008,Hugo,Garcia,hugo.garcia@email.com,Madrid,Spain,2023-05-18,Hugo Garcia
8,C009,Iris,Tanaka,iris.tanaka@email.com,Tokyo,Japan,2023-07-22,Iris Tanaka
9,C010,Jack,Brown,jack.brown@email.com,Sydney,Australia,2023-10-01,Jack Brown
10,C011,Karen,White,unknown@unknown.com,Chicago,USA,2023-11-14,Karen White
11,C012,Leo,Fernandez,leo.f@email.com,Sao Paulo,Brazil,2024-01-09,Leo Fernandez

In [16]:
# read orders.csv file and print the first 5 rows
path = pathlib.Path("C:/Users/mamad/Documents/Databricks/sales_data_engineering_pipeline/data/raw/orders.csv")
orders_df = pd.read_csv(path)
display(orders_df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct
0,O001,C001,P001,1.0,2024-01-05,delivered,0.05
1,O002,C002,P002,2.0,2024-01-07,delivered,0.00
2,O003,C003,P007,1.0,2024-01-10,shipped,0.10
3,O004,C004,P012,3.0,2024-01-12,delivered,0.00
4,O005,C005,P005,1.0,2024-01-15,delivered,0.15
5,O006,C001,P003,2.0,2024-01-18,delivered,0.00
6,O007,C006,P004,1.0,2024-01-20,cancelled,0.00
7,O008,C007,P006,1.0,2024-01-22,shipped,0.05
8,O009,C008,P008,2.0,2024-01-25,delivered,0.00
9,O010,C009,P010,NaN,2024-01-28,delivered,0.00
10,O011,C010,P011,5.0,2024-02-01,delivered,0.00
11,O012,C011,P012,1.0,2024-02-03,pending,0.00
12,O013,C012,P001,1.0,2024-02-05,shipped,0.10
13,O014,C002,P009,2.0,2024-02-08,delivered,0.05
14,O015,C003,P002,4.0,2024-02-10,delivered,0.00
15,O016,C004,P007,1.0,2024-02-12,delivered,0.00
16,O017,C005,P003,3.0,2024-02-15,delivered,0.00
17,O018,C001,P012,2.0,2024-02-18,delivered,0.10
18,O019,C007,P004,1.0,2024-02-20,shipped,0.00
19,O020,C009,P001,1.0,2024-02-22,pending,0.05
20,O021,C010,P005,1.0,2024-02-25,delivered,0.00
21,O022,C006,P008,1.0,2024-02-28,delivered,0.00
22,O023,C003,P006,1.0,2024-03-02,cancelled,0.20
23,O024,C012,P010,10.0,2024-03-05,delivered,0.00
24,O025,C008,P011,3.0,2024-03-08,delivered,0.00
25,O026,C001,P007,1.0,2024-03-10,shipped,0.00
26,O027,C004,P012,2.0,2024-03-12,delivered,0.05
27,O028,C002,P001,1.0,2024-03-15,pending,0.00
28,O029,C011,P003,1.0,2024-03-18,delivered,0.00
29,O030,C005,P004,2.0,2024-03-20,delivered,0.00
30,O030,C005,P004,2.0,2024-03-20,delivered,0.00
31,O030,C005,P004,2.0,2024-03-20,delivered,0.00

In [17]:
# Find duplicate rows in orders_df using order_id column
duplicate_orders = orders_df[orders_df.duplicated(subset=["order_id"], keep=False)]
display(duplicate_orders)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct
29,O030,C005,P004,2.0,2024-03-20,delivered,0.0
30,O030,C005,P004,2.0,2024-03-20,delivered,0.0
31,O030,C005,P004,2.0,2024-03-20,delivered,0.0

In [18]:
# Drop duplicate rows from orders_df
orders_df = orders_df.drop_duplicates(subset=["order_id"], keep="first")
display(orders_df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct
0,O001,C001,P001,1.0,2024-01-05,delivered,0.05
1,O002,C002,P002,2.0,2024-01-07,delivered,0.00
2,O003,C003,P007,1.0,2024-01-10,shipped,0.10
3,O004,C004,P012,3.0,2024-01-12,delivered,0.00
4,O005,C005,P005,1.0,2024-01-15,delivered,0.15
5,O006,C001,P003,2.0,2024-01-18,delivered,0.00
6,O007,C006,P004,1.0,2024-01-20,cancelled,0.00
7,O008,C007,P006,1.0,2024-01-22,shipped,0.05
8,O009,C008,P008,2.0,2024-01-25,delivered,0.00
9,O010,C009,P010,NaN,2024-01-28,delivered,0.00
10,O011,C010,P011,5.0,2024-02-01,delivered,0.00
11,O012,C011,P012,1.0,2024-02-03,pending,0.00
12,O013,C012,P001,1.0,2024-02-05,shipped,0.10
13,O014,C002,P009,2.0,2024-02-08,delivered,0.05
14,O015,C003,P002,4.0,2024-02-10,delivered,0.00
15,O016,C004,P007,1.0,2024-02-12,delivered,0.00
16,O017,C005,P003,3.0,2024-02-15,delivered,0.00
17,O018,C001,P012,2.0,2024-02-18,delivered,0.10
18,O019,C007,P004,1.0,2024-02-20,shipped,0.00
19,O020,C009,P001,1.0,2024-02-22,pending,0.05
20,O021,C010,P005,1.0,2024-02-25,delivered,0.00
21,O022,C006,P008,1.0,2024-02-28,delivered,0.00
22,O023,C003,P006,1.0,2024-03-02,cancelled,0.20
23,O024,C012,P010,10.0,2024-03-05,delivered,0.00
24,O025,C008,P011,3.0,2024-03-08,delivered,0.00
25,O026,C001,P007,1.0,2024-03-10,shipped,0.00
26,O027,C004,P012,2.0,2024-03-12,delivered,0.05
27,O028,C002,P001,1.0,2024-03-15,pending,0.00
28,O029,C011,P003,1.0,2024-03-18,delivered,0.00
29,O030,C005,P004,2.0,2024-03-20,delivered,0.00

In [19]:
# Compter the number of unique order_id in orders_df
unique_order_count = orders_df["order_id"].nunique()
print(f"Number of unique order_id in orders_df: {unique_order_count}")

Number of unique order_id in orders_df: 30

In [20]:
# Find missing quantity values in orders_df
missing_quantity = orders_df[orders_df["quantity"].isnull()]
display(missing_quantity)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct
9,O010,C009,P010,NaN,2024-01-28,delivered,0.0

In [21]:
# Fill missing quantity values with 1
orders_df["quantity"] = orders_df["quantity"].fillna(1)
# Change type of quantity column to int
orders_df["quantity"] = orders_df["quantity"].astype(int)
display(orders_df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct
0,O001,C001,P001,1,2024-01-05,delivered,0.05
1,O002,C002,P002,2,2024-01-07,delivered,0.00
2,O003,C003,P007,1,2024-01-10,shipped,0.10
3,O004,C004,P012,3,2024-01-12,delivered,0.00
4,O005,C005,P005,1,2024-01-15,delivered,0.15
5,O006,C001,P003,2,2024-01-18,delivered,0.00
6,O007,C006,P004,1,2024-01-20,cancelled,0.00
7,O008,C007,P006,1,2024-01-22,shipped,0.05
8,O009,C008,P008,2,2024-01-25,delivered,0.00
9,O010,C009,P010,1,2024-01-28,delivered,0.00
10,O011,C010,P011,5,2024-02-01,delivered,0.00
11,O012,C011,P012,1,2024-02-03,pending,0.00
12,O013,C012,P001,1,2024-02-05,shipped,0.10
13,O014,C002,P009,2,2024-02-08,delivered,0.05
14,O015,C003,P002,4,2024-02-10,delivered,0.00
15,O016,C004,P007,1,2024-02-12,delivered,0.00
16,O017,C005,P003,3,2024-02-15,delivered,0.00
17,O018,C001,P012,2,2024-02-18,delivered,0.10
18,O019,C007,P004,1,2024-02-20,shipped,0.00
19,O020,C009,P001,1,2024-02-22,pending,0.05
20,O021,C010,P005,1,2024-02-25,delivered,0.00
21,O022,C006,P008,1,2024-02-28,delivered,0.00
22,O023,C003,P006,1,2024-03-02,cancelled,0.20
23,O024,C012,P010,10,2024-03-05,delivered,0.00
24,O025,C008,P011,3,2024-03-08,delivered,0.00
25,O026,C001,P007,1,2024-03-10,shipped,0.00
26,O027,C004,P012,2,2024-03-12,delivered,0.05
27,O028,C002,P001,1,2024-03-15,pending,0.00
28,O029,C011,P003,1,2024-03-18,delivered,0.00
29,O030,C005,P004,2,2024-03-20,delivered,0.00

In [22]:
# Parse order_date column to datetime format
orders_df["order_date"] = pd.to_datetime(orders_df["order_date"])
display(orders_df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct
0,O001,C001,P001,1,2024-01-05,delivered,0.05
1,O002,C002,P002,2,2024-01-07,delivered,0.00
2,O003,C003,P007,1,2024-01-10,shipped,0.10
3,O004,C004,P012,3,2024-01-12,delivered,0.00
4,O005,C005,P005,1,2024-01-15,delivered,0.15
5,O006,C001,P003,2,2024-01-18,delivered,0.00
6,O007,C006,P004,1,2024-01-20,cancelled,0.00
7,O008,C007,P006,1,2024-01-22,shipped,0.05
8,O009,C008,P008,2,2024-01-25,delivered,0.00
9,O010,C009,P010,1,2024-01-28,delivered,0.00
10,O011,C010,P011,5,2024-02-01,delivered,0.00
11,O012,C011,P012,1,2024-02-03,pending,0.00
12,O013,C012,P001,1,2024-02-05,shipped,0.10
13,O014,C002,P009,2,2024-02-08,delivered,0.05
14,O015,C003,P002,4,2024-02-10,delivered,0.00
15,O016,C004,P007,1,2024-02-12,delivered,0.00
16,O017,C005,P003,3,2024-02-15,delivered,0.00
17,O018,C001,P012,2,2024-02-18,delivered,0.10
18,O019,C007,P004,1,2024-02-20,shipped,0.00
19,O020,C009,P001,1,2024-02-22,pending,0.05
20,O021,C010,P005,1,2024-02-25,delivered,0.00
21,O022,C006,P008,1,2024-02-28,delivered,0.00
22,O023,C003,P006,1,2024-03-02,cancelled,0.20
23,O024,C012,P010,10,2024-03-05,delivered,0.00
24,O025,C008,P011,3,2024-03-08,delivered,0.00
25,O026,C001,P007,1,2024-03-10,shipped,0.00
26,O027,C004,P012,2,2024-03-12,delivered,0.05
27,O028,C002,P001,1,2024-03-15,pending,0.00
28,O029,C011,P003,1,2024-03-18,delivered,0.00
29,O030,C005,P004,2,2024-03-20,delivered,0.00

In [24]:
invalid_dates = orders_df["order_date"].isna().sum()
print(f"Number of invalid dates in order_date column: {invalid_dates}")

Number of invalid dates in order_date column: 0

In [26]:
# Validate status column values
valid_statuses = ["pending", "shipped", "delivered", "cancelled"]
invalid_statuses = orders_df[~orders_df["status"].isin(valid_statuses)]
display(invalid_statuses)

Empty DataFrame
Columns: [order_id, customer_id, product_id, quantity, order_date, status, discount_pct]
Index: []

In [27]:
# Ensure that status column have only ["pending", "shipped", "delivered", "cancelled"
orders_df = orders_df[orders_df["status"].isin(valid_statuses)]
display(orders_df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct
0,O001,C001,P001,1,2024-01-05,delivered,0.05
1,O002,C002,P002,2,2024-01-07,delivered,0.00
2,O003,C003,P007,1,2024-01-10,shipped,0.10
3,O004,C004,P012,3,2024-01-12,delivered,0.00
4,O005,C005,P005,1,2024-01-15,delivered,0.15
5,O006,C001,P003,2,2024-01-18,delivered,0.00
6,O007,C006,P004,1,2024-01-20,cancelled,0.00
7,O008,C007,P006,1,2024-01-22,shipped,0.05
8,O009,C008,P008,2,2024-01-25,delivered,0.00
9,O010,C009,P010,1,2024-01-28,delivered,0.00
10,O011,C010,P011,5,2024-02-01,delivered,0.00
11,O012,C011,P012,1,2024-02-03,pending,0.00
12,O013,C012,P001,1,2024-02-05,shipped,0.10
13,O014,C002,P009,2,2024-02-08,delivered,0.05
14,O015,C003,P002,4,2024-02-10,delivered,0.00
15,O016,C004,P007,1,2024-02-12,delivered,0.00
16,O017,C005,P003,3,2024-02-15,delivered,0.00
17,O018,C001,P012,2,2024-02-18,delivered,0.10
18,O019,C007,P004,1,2024-02-20,shipped,0.00
19,O020,C009,P001,1,2024-02-22,pending,0.05
20,O021,C010,P005,1,2024-02-25,delivered,0.00
21,O022,C006,P008,1,2024-02-28,delivered,0.00
22,O023,C003,P006,1,2024-03-02,cancelled,0.20
23,O024,C012,P010,10,2024-03-05,delivered,0.00
24,O025,C008,P011,3,2024-03-08,delivered,0.00
25,O026,C001,P007,1,2024-03-10,shipped,0.00
26,O027,C004,P012,2,2024-03-12,delivered,0.05
27,O028,C002,P001,1,2024-03-15,pending,0.00
28,O029,C011,P003,1,2024-03-18,delivered,0.00
29,O030,C005,P004,2,2024-03-20,delivered,0.00

In [28]:
# Fill missing discount values with 0.0
orders_df["discount_pct"] = orders_df["discount_pct"].fillna(0.0)
# Change type of discount column to float
orders_df["discount_pct"] = orders_df["discount_pct"].astype(float)
display(orders_df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct
0,O001,C001,P001,1,2024-01-05,delivered,0.05
1,O002,C002,P002,2,2024-01-07,delivered,0.00
2,O003,C003,P007,1,2024-01-10,shipped,0.10
3,O004,C004,P012,3,2024-01-12,delivered,0.00
4,O005,C005,P005,1,2024-01-15,delivered,0.15
5,O006,C001,P003,2,2024-01-18,delivered,0.00
6,O007,C006,P004,1,2024-01-20,cancelled,0.00
7,O008,C007,P006,1,2024-01-22,shipped,0.05
8,O009,C008,P008,2,2024-01-25,delivered,0.00
9,O010,C009,P010,1,2024-01-28,delivered,0.00
10,O011,C010,P011,5,2024-02-01,delivered,0.00
11,O012,C011,P012,1,2024-02-03,pending,0.00
12,O013,C012,P001,1,2024-02-05,shipped,0.10
13,O014,C002,P009,2,2024-02-08,delivered,0.05
14,O015,C003,P002,4,2024-02-10,delivered,0.00
15,O016,C004,P007,1,2024-02-12,delivered,0.00
16,O017,C005,P003,3,2024-02-15,delivered,0.00
17,O018,C001,P012,2,2024-02-18,delivered,0.10
18,O019,C007,P004,1,2024-02-20,shipped,0.00
19,O020,C009,P001,1,2024-02-22,pending,0.05
20,O021,C010,P005,1,2024-02-25,delivered,0.00
21,O022,C006,P008,1,2024-02-28,delivered,0.00
22,O023,C003,P006,1,2024-03-02,cancelled,0.20
23,O024,C012,P010,10,2024-03-05,delivered,0.00
24,O025,C008,P011,3,2024-03-08,delivered,0.00
25,O026,C001,P007,1,2024-03-10,shipped,0.00
26,O027,C004,P012,2,2024-03-12,delivered,0.05
27,O028,C002,P001,1,2024-03-15,pending,0.00
28,O029,C011,P003,1,2024-03-18,delivered,0.00
29,O030,C005,P004,2,2024-03-20,delivered,0.00

In [30]:
# Reset index of orders_df after dropping duplicates and invalid statuses
orders_df = orders_df.reset_index(drop=True)
display(orders_df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct
0,O001,C001,P001,1,2024-01-05,delivered,0.05
1,O002,C002,P002,2,2024-01-07,delivered,0.00
2,O003,C003,P007,1,2024-01-10,shipped,0.10
3,O004,C004,P012,3,2024-01-12,delivered,0.00
4,O005,C005,P005,1,2024-01-15,delivered,0.15
5,O006,C001,P003,2,2024-01-18,delivered,0.00
6,O007,C006,P004,1,2024-01-20,cancelled,0.00
7,O008,C007,P006,1,2024-01-22,shipped,0.05
8,O009,C008,P008,2,2024-01-25,delivered,0.00
9,O010,C009,P010,1,2024-01-28,delivered,0.00
10,O011,C010,P011,5,2024-02-01,delivered,0.00
11,O012,C011,P012,1,2024-02-03,pending,0.00
12,O013,C012,P001,1,2024-02-05,shipped,0.10
13,O014,C002,P009,2,2024-02-08,delivered,0.05
14,O015,C003,P002,4,2024-02-10,delivered,0.00
15,O016,C004,P007,1,2024-02-12,delivered,0.00
16,O017,C005,P003,3,2024-02-15,delivered,0.00
17,O018,C001,P012,2,2024-02-18,delivered,0.10
18,O019,C007,P004,1,2024-02-20,shipped,0.00
19,O020,C009,P001,1,2024-02-22,pending,0.05
20,O021,C010,P005,1,2024-02-25,delivered,0.00
21,O022,C006,P008,1,2024-02-28,delivered,0.00
22,O023,C003,P006,1,2024-03-02,cancelled,0.20
23,O024,C012,P010,10,2024-03-05,delivered,0.00
24,O025,C008,P011,3,2024-03-08,delivered,0.00
25,O026,C001,P007,1,2024-03-10,shipped,0.00
26,O027,C004,P012,2,2024-03-12,delivered,0.05
27,O028,C002,P001,1,2024-03-15,pending,0.00
28,O029,C011,P003,1,2024-03-18,delivered,0.00
29,O030,C005,P004,2,2024-03-20,delivered,0.00

In [5]:
# read products.csv file and print the first 5 rows
path = pathlib.Path("C:/Users/mamad/Documents/Databricks/sales_data_engineering_pipeline/data/raw/products.csv")
products_df = pd.read_csv(path)
display(products_df)

   product_id                 name     category  unit_price  stock
0        P001        Laptop Pro 15  Electronics     1299.99     50
1        P002       Wireless Mouse  Electronics       29.99    200
2        P003            USB-C Hub  Electronics       49.99    150
3        P004  Mechanical Keyboard  Electronics       89.99     80
4        P005        Standing Desk    Furniture      399.99     30
5        P006      Ergonomic Chair    Furniture      599.99     20
6        P007          Monitor 27"  Electronics      349.99     60
7        P008            Webcam HD  Electronics       79.99    100
8        P009        Desk Lamp LED    Furniture       45.99    120
9        P010          Notebook A4   Stationery        4.99    500
10       P011              Pen Set   Stationery       12.99    300
11       P012        Headphones BT  Electronics      149.99     75

In [40]:
# Drop duplicate rows from products_df
products_df = products_df.drop_duplicates(subset=["product_id"])
# Change unit_orice column to numeric type 
products_df["unit_price"] = pd.to_numeric(products_df["unit_price"], errors="coerce")
#drop rows with missing unit_price values
products_df = products_df.dropna(subset=["unit_price"])
# Reset index of products_df after dropping duplicates and missing values
products_df = products_df.reset_index(drop=True)
display(products_df)

   product_id                 name     category  unit_price  stock
0        P001        Laptop Pro 15  Electronics     1299.99     50
1        P002       Wireless Mouse  Electronics       29.99    200
2        P003            USB-C Hub  Electronics       49.99    150
3        P004  Mechanical Keyboard  Electronics       89.99     80
4        P005        Standing Desk    Furniture      399.99     30
5        P006      Ergonomic Chair    Furniture      599.99     20
6        P007          Monitor 27"  Electronics      349.99     60
7        P008            Webcam HD  Electronics       79.99    100
8        P009        Desk Lamp LED    Furniture       45.99    120
9        P010          Notebook A4   Stationery        4.99    500
10       P011              Pen Set   Stationery       12.99    300
11       P012        Headphones BT  Electronics      149.99     75

In [42]:
# Join orders, customers, products dataframes on customer_id and product_id columns
merged_df = orders_df.merge(customers_df, on="customer_id", how="left", validate="m:1").merge(products_df, on="product_id", how="left", validate="m:1")
display(merged_df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct,first_name,last_name,email,city,country,signup_date,full_name,name,category,unit_price,stock
0,O001,C001,P001,1,2024-01-05,delivered,0.05,Alice,Martin,alice.martin@email.com,Paris,France,2022-01-15,Alice Martin,Laptop Pro 15,Electronics,1299.99,50
1,O002,C002,P002,2,2024-01-07,delivered,0.00,Bob,Dupont,bob.dupont@email.com,Lyon,France,2022-03-22,Bob Dupont,Wireless Mouse,Electronics,29.99,200
2,O003,C003,P007,1,2024-01-10,shipped,0.10,Clara,Smith,clara.smith@email.com,London,UK,2022-05-10,Clara Smith,"Monitor 27""",Electronics,349.99,60
3,O004,C004,P012,3,2024-01-12,delivered,0.00,David,Johnson,david.j@email.com,New York,USA,2022-07-08,David Johnson,Headphones BT,Electronics,149.99,75
4,O005,C005,P005,1,2024-01-15,delivered,0.15,Eva,Müller,eva.muller@email.com,Berlin,Germany,2022-09-30,Eva Müller,Standing Desk,Furniture,399.99,30
5,O006,C001,P003,2,2024-01-18,delivered,0.00,Alice,Martin,alice.martin@email.com,Paris,France,2022-01-15,Alice Martin,USB-C Hub,Electronics,49.99,150
6,O007,C006,P004,1,2024-01-20,cancelled,0.00,Frank,Rossi,frank.rossi@email.com,Rome,Italy,2023-01-12,Frank Rossi,Mechanical Keyboard,Electronics,89.99,80
7,O008,C007,P006,1,2024-01-22,shipped,0.05,Grace,Lee,grace.lee@email.com,Seoul,South Korea,2023-03-05,Grace Lee,Ergonomic Chair,Furniture,599.99,20
8,O009,C008,P008,2,2024-01-25,delivered,0.00,Hugo,Garcia,hugo.garcia@email.com,Madrid,Spain,2023-05-18,Hugo Garcia,Webcam HD,Electronics,79.99,100
9,O010,C009,P010,1,2024-01-28,delivered,0.00,Iris,Tanaka,iris.tanaka@email.com,Tokyo,Japan,2023-07-22,Iris Tanaka,Notebook A4,Stationery,4.99,500
10,O011,C010,P011,5,2024-02-01,delivered,0.00,Jack,Brown,jack.brown@email.com,Sydney,Australia,2023-10-01,Jack Brown,Pen Set,Stationery,12.99,300
11,O012,C011,P012,1,2024-02-03,pending,0.00,Karen,White,unknown@unknown.com,Chicago,USA,2023-11-14,Karen White,Headphones BT,Electronics,149.99,75
12,O013,C012,P001,1,2024-02-05,shipped,0.10,Leo,Fernandez,leo.f@email.com,Sao Paulo,Brazil,2024-01-09,Leo Fernandez,Laptop Pro 15,Electronics,1299.99,50
13,O014,C002,P009,2,2024-02-08,delivered,0.05,Bob,Dupont,bob.dupont@email.com,Lyon,France,2022-03-22,Bob Dupont,Desk Lamp LED,Furniture,45.99,120
14,O015,C003,P002,4,2024-02-10,delivered,0.00,Clara,Smith,clara.smith@email.com,London,UK,2022-05-10,Clara Smith,Wireless Mouse,Electronics,29.99,200
15,O016,C004,P007,1,2024-02-12,delivered,0.00,David,Johnson,david.j@email.com,New York,USA,2022-07-08,David Johnson,"Monitor 27""",Electronics,349.99,60
16,O017,C005,P003,3,2024-02-15,delivered,0.00,Eva,Müller,eva.muller@email.com,Berlin,Germany,2022-09-30,Eva Müller,USB-C Hub,Electronics,49.99,150
17,O018,C001,P012,2,2024-02-18,delivered,0.10,Alice,Martin,alice.martin@email.com,Paris,France,2022-01-15,Alice Martin,Headphones BT,Electronics,149.99,75
18,O019,C007,P004,1,2024-02-20,shipped,0.00,Grace,Lee,grace.lee@email.com,Seoul,South Korea,2023-03-05,Grace Lee,Mechanical Keyboard,Electronics,89.99,80
19,O020,C009,P001,1,2024-02-22,pending,0.05,Iris,Tanaka,iris.tanaka@email.com,Tokyo,Japan,2023-07-22,Iris Tanaka,Laptop Pro 15,Electronics,1299.99,50
20,O021,C010,P005,1,2024-02-25,delivered,0.00,Jack,Brown,jack.brown@email.com,Sydney,Australia,2023-10-01,Jack Brown,Standing Desk,Furniture,399.99,30
21,O022,C006,P008,1,2024-02-28,delivered,0.00,Frank,Rossi,frank.rossi@email.com,Rome,Italy,2023-01-12,Frank Rossi,Webcam HD,Electronics,79.99,100
22,O023,C003,P006,1,2024-03-02,cancelled,0.20,Clara,Smith,clara.smith@email.com,London,UK,2022-05-10,Clara Smith,Ergonomic Chair,Furniture,599.99,20
23,O024,C012,P010,10,2024-03-05,delivered,0.00,Leo,Fernandez,leo.f@email.com,Sao Paulo,Brazil,2024-01-09,Leo Fernandez,Notebook A4,Stationery,4.99,500
24,O025,C008,P011,3,2024-03-08,delivered,0.00,Hugo,Garcia,hugo.garcia@email.com,Madrid,Spain,2023-05-18,Hugo Garcia,Pen Set,Stationery,12.99,300
25,O026,C001,P007,1,2024-03-10,shipped,0.00,Alice,Martin,alice.martin@email.com,Paris,France,2022-01-15,Alice Martin,"Monitor 27""",Electronics,349.99,60
26,O027,C004,P012,2,2024-03-12,delivered,0.05,David,Johnson,david.j@email.com,New York,USA,2022-07-08,David Johnson,Headphones BT,Electronics,149.99,75
27,O028,C002,P001,1,2024-03-15,pending,0.00,Bob,Dupont,bob.dupont@email.com,Lyon,France,2022-03-22,Bob Dupont,Laptop Pro 15,Electronics,1299.99,50
28,O029,C011,P003,1,2024-03-18,delivered,0.00,Karen,White,unknown@unknown.com,Chicago,USA,2023-11-14,Karen White,USB-C Hub,Electronics,49.99,150
29,O030,C005,P004,2,2024-03-20,delivered,0.00,Eva,Müller,eva.muller@email.com,Berlin,Germany,2022-09-30,Eva Müller,Mechanical Keyboard,Electronics,89.99,80

In [44]:
# Computing  financial metrics like gross_revenue, discount_amount, net_revenue, estimated_cost, gross_profit, order_year_month
merged_df["gross_revenue"] = merged_df["quantity"] * merged_df["unit_price"]
merged_df["discount_amount"] = merged_df["gross_revenue"] * merged_df["discount_pct"]
merged_df["net_revenue"] = merged_df["gross_revenue"] - merged_df["discount_amount"]
merged_df["estimated_cost"] = merged_df["gross_revenue"] * (1 - 0.3)
merged_df["gross_profit"] = merged_df["net_revenue"] - merged_df["estimated_cost"]
merged_df["order_year_month"] = merged_df["order_date"].dt.to_period("M").astype(str)
display(merged_df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct,first_name,last_name,email,...,name,category,unit_price,stock,gross_revenue,discount_amount,net_revenue,estimated_cost,gross_profit,order_year_month
0,O001,C001,P001,1,2024-01-05,delivered,0.05,Alice,Martin,alice.martin@email.com,...,Laptop Pro 15,Electronics,1299.99,50,1299.99,64.9995,1234.9905,909.993,324.9975,2024-01
1,O002,C002,P002,2,2024-01-07,delivered,0.00,Bob,Dupont,bob.dupont@email.com,...,Wireless Mouse,Electronics,29.99,200,59.98,0.0000,59.9800,41.986,17.9940,2024-01
2,O003,C003,P007,1,2024-01-10,shipped,0.10,Clara,Smith,clara.smith@email.com,...,"Monitor 27""",Electronics,349.99,60,349.99,34.9990,314.9910,244.993,69.9980,2024-01
3,O004,C004,P012,3,2024-01-12,delivered,0.00,David,Johnson,david.j@email.com,...,Headphones BT,Electronics,149.99,75,449.97,0.0000,449.9700,314.979,134.9910,2024-01
4,O005,C005,P005,1,2024-01-15,delivered,0.15,Eva,Müller,eva.muller@email.com,...,Standing Desk,Furniture,399.99,30,399.99,59.9985,339.9915,279.993,59.9985,2024-01
5,O006,C001,P003,2,2024-01-18,delivered,0.00,Alice,Martin,alice.martin@email.com,...,USB-C Hub,Electronics,49.99,150,99.98,0.0000,99.9800,69.986,29.9940,2024-01
6,O007,C006,P004,1,2024-01-20,cancelled,0.00,Frank,Rossi,frank.rossi@email.com,...,Mechanical Keyboard,Electronics,89.99,80,89.99,0.0000,89.9900,62.993,26.9970,2024-01
7,O008,C007,P006,1,2024-01-22,shipped,0.05,Grace,Lee,grace.lee@email.com,...,Ergonomic Chair,Furniture,599.99,20,599.99,29.9995,569.9905,419.993,149.9975,2024-01
8,O009,C008,P008,2,2024-01-25,delivered,0.00,Hugo,Garcia,hugo.garcia@email.com,...,Webcam HD,Electronics,79.99,100,159.98,0.0000,159.9800,111.986,47.9940,2024-01
9,O010,C009,P010,1,2024-01-28,delivered,0.00,Iris,Tanaka,iris.tanaka@email.com,...,Notebook A4,Stationery,4.99,500,4.99,0.0000,4.9900,3.493,1.4970,2024-01
10,O011,C010,P011,5,2024-02-01,delivered,0.00,Jack,Brown,jack.brown@email.com,...,Pen Set,Stationery,12.99,300,64.95,0.0000,64.9500,45.465,19.4850,2024-02
11,O012,C011,P012,1,2024-02-03,pending,0.00,Karen,White,unknown@unknown.com,...,Headphones BT,Electronics,149.99,75,149.99,0.0000,149.9900,104.993,44.9970,2024-02
12,O013,C012,P001,1,2024-02-05,shipped,0.10,Leo,Fernandez,leo.f@email.com,...,Laptop Pro 15,Electronics,1299.99,50,1299.99,129.9990,1169.9910,909.993,259.9980,2024-02
13,O014,C002,P009,2,2024-02-08,delivered,0.05,Bob,Dupont,bob.dupont@email.com,...,Desk Lamp LED,Furniture,45.99,120,91.98,4.5990,87.3810,64.386,22.9950,2024-02
14,O015,C003,P002,4,2024-02-10,delivered,0.00,Clara,Smith,clara.smith@email.com,...,Wireless Mouse,Electronics,29.99,200,119.96,0.0000,119.9600,83.972,35.9880,2024-02
15,O016,C004,P007,1,2024-02-12,delivered,0.00,David,Johnson,david.j@email.com,...,"Monitor 27""",Electronics,349.99,60,349.99,0.0000,349.9900,244.993,104.9970,2024-02
16,O017,C005,P003,3,2024-02-15,delivered,0.00,Eva,Müller,eva.muller@email.com,...,USB-C Hub,Electronics,49.99,150,149.97,0.0000,149.9700,104.979,44.9910,2024-02
17,O018,C001,P012,2,2024-02-18,delivered,0.10,Alice,Martin,alice.martin@email.com,...,Headphones BT,Electronics,149.99,75,299.98,29.9980,269.9820,209.986,59.9960,2024-02
18,O019,C007,P004,1,2024-02-20,shipped,0.00,Grace,Lee,grace.lee@email.com,...,Mechanical Keyboard,Electronics,89.99,80,89.99,0.0000,89.9900,62.993,26.9970,2024-02
19,O020,C009,P001,1,2024-02-22,pending,0.05,Iris,Tanaka,iris.tanaka@email.com,...,Laptop Pro 15,Electronics,1299.99,50,1299.99,64.9995,1234.9905,909.993,324.9975,2024-02
20,O021,C010,P005,1,2024-02-25,delivered,0.00,Jack,Brown,jack.brown@email.com,...,Standing Desk,Furniture,399.99,30,399.99,0.0000,399.9900,279.993,119.9970,2024-02
21,O022,C006,P008,1,2024-02-28,delivered,0.00,Frank,Rossi,frank.rossi@email.com,...,Webcam HD,Electronics,79.99,100,79.99,0.0000,79.9900,55.993,23.9970,2024-02
22,O023,C003,P006,1,2024-03-02,cancelled,0.20,Clara,Smith,clara.smith@email.com,...,Ergonomic Chair,Furniture,599.99,20,599.99,119.9980,479.9920,419.993,59.9990,2024-03
23,O024,C012,P010,10,2024-03-05,delivered,0.00,Leo,Fernandez,leo.f@email.com,...,Notebook A4,Stationery,4.99,500,49.90,0.0000,49.9000,34.930,14.9700,2024-03
24,O025,C008,P011,3,2024-03-08,delivered,0.00,Hugo,Garcia,hugo.garcia@email.com,...,Pen Set,Stationery,12.99,300,38.97,0.0000,38.9700,27.279,11.6910,2024-03
25,O026,C001,P007,1,2024-03-10,shipped,0.00,Alice,Martin,alice.martin@email.com,...,"Monitor 27""",Electronics,349.99,60,349.99,0.0000,349.9900,244.993,104.9970,2024-03
26,O027,C004,P012,2,2024-03-12,delivered,0.05,David,Johnson,david.j@email.com,...,Headphones BT,Electronics,149.99,75,299.98,14.9990,284.9810,209.986,74.9950,2024-03
27,O028,C002,P001,1,2024-03-15,pending,0.00,Bob,Dupont,bob.dupont@email.com,...,Laptop Pro 15,Electronics,1299.99,50,1299.99,0.0000,1299.9900,909.993,389.9970,2024-03
28,O029,C011,P003,1,2024-03-18,delivered,0.00,Karen,White,unknown@unknown.com,...,USB-C Hub,Electronics,49.99,150,49.99,0.0000,49.9900,34.993,14.9970,2024-03
29,O030,C005,P004,2,2024-03-20,delivered,0.00,Eva,Müller,eva.muller@email.com,...,Mechanical Keyboard,Electronics,89.99,80,179.98,0.0000,179.9800,125.986,53.9940,2024-03

In [45]:
# Build sales summary based on order_year_month and category columns with metrics like total_orders, total_quantity, gross_revenue, net_revenue, gross_profit, avg_discount_pct
sales_summary = merged_df.groupby(["order_year_month", "category"]).agg(
    total_orders=("order_id", "count"),
    total_quantity=("quantity", "sum"),
    gross_revenue=("gross_revenue", "sum"),
    net_revenue=("net_revenue", "sum"),
    gross_profit=("gross_profit", "sum"),
    avg_discount_pct=("discount_pct", "mean")
).reset_index()
display(sales_summary)

,order_year_month,category,total_orders,total_quantity,gross_revenue,net_revenue,gross_profit,avg_discount_pct
0,2024-01,Electronics,7,12,2509.88,2409.8815,652.9655,0.021429
1,2024-01,Furniture,2,2,999.98,909.9820,209.9960,0.100000
2,2024-01,Stationery,1,1,4.99,4.9900,1.4970,0.000000
3,2024-02,Electronics,9,15,3839.85,3614.8535,926.9585,0.027778
4,2024-02,Furniture,2,3,491.97,487.3710,142.9920,0.025000
5,2024-02,Stationery,1,5,64.95,64.9500,19.4850,0.000000
6,2024-03,Electronics,5,7,2179.93,2164.9310,638.9800,0.010000
7,2024-03,Furniture,1,1,599.99,479.9920,59.9990,0.200000
8,2024-03,Stationery,2,13,88.87,88.8700,26.6610,0.000000

In [ ]:
# Crate an histogrm of profit_margin_pct column in sales_summary

In [46]:
# Calculate profit margin percentage and add it as a new column to sales_summary a,d round it to 2 decimal places
sales_summary["profit_margin_pct"] = (sales_summary["gross_profit"] / sales_summary["gross_revenue"] * 100).round(2)
display(sales_summary)

,order_year_month,category,total_orders,total_quantity,gross_revenue,net_revenue,gross_profit,avg_discount_pct,profit_margin_pct
0,2024-01,Electronics,7,12,2509.88,2409.8815,652.9655,0.021429,26.02
1,2024-01,Furniture,2,2,999.98,909.9820,209.9960,0.100000,21.00
2,2024-01,Stationery,1,1,4.99,4.9900,1.4970,0.000000,30.00
3,2024-02,Electronics,9,15,3839.85,3614.8535,926.9585,0.027778,24.14
4,2024-02,Furniture,2,3,491.97,487.3710,142.9920,0.025000,29.07
5,2024-02,Stationery,1,5,64.95,64.9500,19.4850,0.000000,30.00
6,2024-03,Electronics,5,7,2179.93,2164.9310,638.9800,0.010000,29.31
7,2024-03,Furniture,1,1,599.99,479.9920,59.9990,0.200000,10.00
8,2024-03,Stationery,2,13,88.87,88.8700,26.6610,0.000000,30.00

In [3]:
import sqlite3
import pandas as pd
from pathlib import Path

# Chemin absolu vers la base — fonctionne quel que soit le répertoire courant du notebook
DB_PATH = Path(__file__).parent.parent / "data" / "output" / "sales.db" if "__file__" in dir() else Path("c:/Users/mamad/Documents/Databricks/Data-engineering-project/data/output/sales.db")

con = sqlite3.connect(DB_PATH)

# Lister les tables de la base de données
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", con)
print(tables)

              name
0  orders_enriched
1    sales_summary

In [6]:
# Requêter les commandes enrichies
df = pd.read_sql("SELECT * FROM orders_enriched LIMIT 10", con)
display(df)

,order_id,customer_id,product_id,quantity,order_date,status,discount_pct,full_name,city,country,signup_date,name,category,unit_price,gross_revenue,discount_amount,net_revenue,estimated_cost,gross_profit,order_year_month
0,O001,C001,P001,1,2024-01-05 00:00:00.000000,delivered,0.05,Alice Martin,Paris,France,2022-01-15 00:00:00.000000,Laptop Pro 15,Electronics,1299.99,1299.99,64.9995,1234.9905,909.993,324.9975,2024-01
1,O002,C002,P002,2,2024-01-07 00:00:00.000000,delivered,0.00,Bob Dupont,Lyon,France,2022-03-22 00:00:00.000000,Wireless Mouse,Electronics,29.99,59.98,0.0000,59.9800,41.986,17.9940,2024-01
2,O003,C003,P007,1,2024-01-10 00:00:00.000000,shipped,0.10,Clara Smith,London,UK,2022-05-10 00:00:00.000000,"Monitor 27""",Electronics,349.99,349.99,34.9990,314.9910,244.993,69.9980,2024-01
3,O004,C004,P012,3,2024-01-12 00:00:00.000000,delivered,0.00,David Johnson,New York,USA,2022-07-08 00:00:00.000000,Headphones BT,Electronics,149.99,449.97,0.0000,449.9700,314.979,134.9910,2024-01
4,O005,C005,P005,1,2024-01-15 00:00:00.000000,delivered,0.15,Eva Müller,Berlin,Germany,2022-09-30 00:00:00.000000,Standing Desk,Furniture,399.99,399.99,59.9985,339.9915,279.993,59.9985,2024-01
5,O006,C001,P003,2,2024-01-18 00:00:00.000000,delivered,0.00,Alice Martin,Paris,France,2022-01-15 00:00:00.000000,USB-C Hub,Electronics,49.99,99.98,0.0000,99.9800,69.986,29.9940,2024-01
6,O007,C006,P004,1,2024-01-20 00:00:00.000000,cancelled,0.00,Frank Rossi,Rome,Italy,2023-01-12 00:00:00.000000,Mechanical Keyboard,Electronics,89.99,89.99,0.0000,89.9900,62.993,26.9970,2024-01
7,O008,C007,P006,1,2024-01-22 00:00:00.000000,shipped,0.05,Grace Lee,Seoul,South Korea,2023-03-05 00:00:00.000000,Ergonomic Chair,Furniture,599.99,599.99,29.9995,569.9905,419.993,149.9975,2024-01
8,O009,C008,P008,2,2024-01-25 00:00:00.000000,delivered,0.00,Hugo Garcia,Madrid,Spain,2023-05-18 00:00:00.000000,Webcam HD,Electronics,79.99,159.98,0.0000,159.9800,111.986,47.9940,2024-01
9,O010,C009,P010,1,2024-01-28 00:00:00.000000,delivered,0.00,Iris Tanaka,Tokyo,Japan,2023-07-22 00:00:00.000000,Notebook A4,Stationery,4.99,4.99,0.0000,4.9900,3.493,1.4970,2024-01